import { Exercise } from "@/types";

export const beginnerExercises: Exercise[] = [
  {
    id: "b1",
    title: "SELECT básico",
    description: "Obtén todos los usuarios",
    difficulty: "beginner",
    instructions: "Escribe una consulta SELECT que devuelva todas las columnas de la tabla `usuarios`.",
    hint: "Usa SELECT * FROM usuarios",
    solution: "SELECT * FROM usuarios;",
    explanation: "SELECT * selecciona todas las columnas de la tabla especificada.",
    tableSchema: "usuarios (id INT, nombre TEXT, email TEXT, edad INT, ciudad TEXT)",
    initialData: "INSERT INTO usuarios VALUES (1, 'Ana', 'ana@email.com', 28, 'Madrid'), (2, 'Carlos', 'carlos@email.com', 32, 'Barcelona'), (3, 'María', 'maria@email.com', 25, 'Valencia');",
  },
  {
    id: "b2",
    title: "SELECT con columnas específicas",
    description: "Obtén solo nombres y emails",
    difficulty: "beginner",
    instructions: "Escribe una consulta que devuelva solo las columnas `nombre` y `email` de la tabla `usuarios`.",
    hint: "Especifica los nombres de las columnas separados por comas",
    solution: "SELECT nombre, email FROM usuarios;",
    explanation: "Seleccionar columnas específicas es más eficiente que SELECT *.",
    tableSchema: "usuarios (id INT, nombre TEXT, email TEXT, edad INT, ciudad TEXT)",
    initialData: "INSERT INTO usuarios VALUES (1, 'Ana', 'ana@email.com', 28, 'Madrid'), (2, 'Carlos', 'carlos@email.com', 32, 'Barcelona');",
  },
  {
    id: "b3",
    title: "WHERE básico",
    description: "Filtra usuarios por ciudad",
    difficulty: "beginner",
    instructions: "Encuentra todos los usuarios que viven en 'Madrid'.",
    hint: "Usa WHERE ciudad = 'Madrid'",
    solution: "SELECT * FROM usuarios WHERE ciudad = 'Madrid';",
    explanation: "WHERE filtra filas según una condición.",
    tableSchema: "usuarios (id INT, nombre TEXT, email TEXT, edad INT, ciudad TEXT)",
    initialData: "INSERT INTO usuarios VALUES (1, 'Ana', 'ana@email.com', 28, 'Madrid'), (2, 'Carlos', 'carlos@email.com', 32, 'Barcelona'), (3, 'Laura', 'laura@email.com', 30, 'Madrid');",
  },
  {
    id: "b4",
    title: "INSERT",
    description: "Inserta un nuevo usuario",
    difficulty: "beginner",
    instructions: "Inserta un nuevo usuario llamado 'Pedro' con email 'pedro@email.com', edad 35 y ciudad 'Sevilla'.",
    hint: "INSERT INTO usuarios (nombre, email, edad, ciudad) VALUES (...)",
    solution: "INSERT INTO usuarios (nombre, email, edad, ciudad) VALUES ('Pedro', 'pedro@email.com', 35, 'Sevilla');",
    explanation: "INSERT agrega nuevas filas a una tabla.",
    tableSchema: "usuarios (id INT, nombre TEXT, email TEXT, edad INT, ciudad TEXT)",
    initialData: "INSERT INTO usuarios VALUES (1, 'Ana', 'ana@email.com', 28, 'Madrid');",
  },
  {
    id: "b5",
    title: "UPDATE",
    description: "Actualiza el email de un usuario",
    difficulty: "beginner",
    instructions: "Actualiza el email del usuario con id=1 a 'ana.nuevo@email.com'.",
    hint: "Usa WHERE id = 1 para especificar el usuario",
    solution: "UPDATE usuarios SET email = 'ana.nuevo@email.com' WHERE id = 1;",
    explanation: "UPDATE modifica filas existentes. Siempre usa WHERE.",
    tableSchema: "usuarios (id INT, nombre TEXT, email TEXT)",
    initialData: "INSERT INTO usuarios VALUES (1, 'Ana', 'ana@email.com'), (2, 'Carlos', 'carlos@email.com');",
  },
  {
    id: "b6",
    title: "DELETE",
    description: "Elimina un usuario",
    difficulty: "beginner",
    instructions: "Elimina el usuario con id=3 de la tabla usuarios.",
    hint: "DELETE FROM usuarios WHERE id = 3",
    solution: "DELETE FROM usuarios WHERE id = 3;",
    explanation: "DELETE elimina filas. Sin WHERE, se eliminan todas.",
    tableSchema: "usuarios (id INT, nombre TEXT, email TEXT)",
    initialData: "INSERT INTO usuarios VALUES (1, 'Ana', 'ana@email.com'), (2, 'Carlos', 'carlos@email.com'), (3, 'María', 'maria@email.com');",
  },
  {
    id: "b7",
    title: "ORDER BY",
    description: "Ordena usuarios por edad",
    difficulty: "beginner",
    instructions: "Selecciona todos los usuarios ordenados por edad de forma descendente.",
    hint: "ORDER BY edad DESC",
    solution: "SELECT * FROM usuarios ORDER BY edad DESC;",
    explanation: "ORDER BY ordena resultados. ASC (por defecto) o DESC.",
    tableSchema: "usuarios (id INT, nombre TEXT, email TEXT, edad INT)",
    initialData: "INSERT INTO usuarios VALUES (1, 'Ana', 'ana@email.com', 28), (2, 'Carlos', 'carlos@email.com', 32), (3, 'María', 'maria@email.com', 25);",
  },
  {
    id: "b8",
    title: "LIMIT",
    description: "Obtén los primeros 2 usuarios",
    difficulty: "beginner",
    instructions: "Selecciona los primeros 2 usuarios ordenados por id.",
    hint: "Usa LIMIT 2 al final de la consulta",
    solution: "SELECT * FROM usuarios ORDER BY id LIMIT 2;",
    explanation: "LIMIT restringe el número de filas devueltas.",
    tableSchema: "usuarios (id INT, nombre TEXT, email TEXT)",
    initialData: "INSERT INTO usuarios VALUES (1, 'Ana', 'ana@email.com'), (2, 'Carlos', 'carlos@email.com'), (3, 'María', 'maria@email.com');",
  },
  {
    id: "b9",
    title: "WHERE con AND",
    description: "Filtra con múltiples condiciones",
    difficulty: "beginner",
    instructions: "Encuentra usuarios de 'Madrid' con edad mayor o igual a 25.",
    hint: "WHERE ciudad = 'Madrid' AND edad >= 25",
    solution: "SELECT * FROM usuarios WHERE ciudad = 'Madrid' AND edad >= 25;",
    explanation: "AND requiere que ambas condiciones sean verdaderas.",
    tableSchema: "usuarios (id INT, nombre TEXT, ciudad TEXT, edad INT)",
    initialData: "INSERT INTO usuarios VALUES (1, 'Ana', 'Madrid', 28), (2, 'Carlos', 'Barcelona', 32), (3, 'Laura', 'Madrid', 22), (4, 'Pedro', 'Madrid', 30);",
  },
  {
    id: "b10",
    title: "WHERE con OR",
    description: "Filtra con condiciones alternativas",
    difficulty: "beginner",
    instructions: "Encuentra usuarios de 'Madrid' o 'Barcelona'.",
    hint: "WHERE ciudad = 'Madrid' OR ciudad = 'Barcelona'",
    solution: "SELECT * FROM usuarios WHERE ciudad = 'Madrid' OR ciudad = 'Barcelona';",
    explanation: "OR devuelve filas que cumplen al menos una condición.",
    tableSchema: "usuarios (id INT, nombre TEXT, ciudad TEXT)",
    initialData: "INSERT INTO usuarios VALUES (1, 'Ana', 'Madrid'), (2, 'Carlos', 'Barcelona'), (3, 'María', 'Valencia'), (4, 'Laura', 'Madrid');",
  },
  {
    id: "b11",
    title: "BETWEEN",
    description: "Filtra por rango de edades",
    difficulty: "beginner",
    instructions: "Selecciona usuarios con edad entre 25 y 35 años.",
    hint: "WHERE edad BETWEEN 25 AND 35",
    solution: "SELECT * FROM usuarios WHERE edad BETWEEN 25 AND 35;",
    explanation: "BETWEEN incluye los valores del límite.",
    tableSchema: "usuarios (id INT, nombre TEXT, edad INT)",
    initialData: "INSERT INTO usuarios VALUES (1, 'Ana', 28), (2, 'Carlos', 32), (3, 'María', 22), (4, 'Pedro', 40);",
  },
  {
    id: "b12",
    title: "LIKE",
    description: "Busca por patrón de texto",
    difficulty: "beginner",
    instructions: "Encuentra usuarios cuyo email termine en '@gmail.com'.",
    hint: "WHERE email LIKE '%@gmail.com'",
    solution: "SELECT * FROM usuarios WHERE email LIKE '%@gmail.com';",
    explanation: "LIKE usa % como comodín (cualquier texto).",
    tableSchema: "usuarios (id INT, nombre TEXT, email TEXT)",
    initialData: "INSERT INTO usuarios VALUES (1, 'Ana', 'ana@gmail.com'), (2, 'Carlos', 'carlos@yahoo.com'), (3, 'María', 'maria@gmail.com');",
  },
  {
    id: "b13",
    title: "IN",
    description: "Filtra por lista de valores",
    difficulty: "beginner",
    instructions: "Selecciona usuarios de 'Madrid', 'Barcelona' o 'Valencia'.",
    hint: "WHERE ciudad IN ('Madrid', 'Barcelona', 'Valencia')",
    solution: "SELECT * FROM usuarios WHERE ciudad IN ('Madrid', 'Barcelona', 'Valencia');",
    explanation: "IN es más limpio que múltiples OR.",
    tableSchema: "usuarios (id INT, nombre TEXT, ciudad TEXT)",
    initialData: "INSERT INTO usuarios VALUES (1, 'Ana', 'Madrid'), (2, 'Carlos', 'Barcelona'), (3, 'María', 'Sevilla'), (4, 'Laura', 'Valencia');",
  },
  {
    id: "b14",
    title: "DISTINCT",
    description: "Valores únicos de una columna",
    difficulty: "beginner",
    instructions: "Obtén las ciudades distintas de las que hay usuarios.",
    hint: "SELECT DISTINCT ciudad FROM usuarios",
    solution: "SELECT DISTINCT ciudad FROM usuarios;",
    explanation: "DISTINCT elimina duplicados del resultado.",
    tableSchema: "usuarios (id INT, nombre TEXT, ciudad TEXT)",
    initialData: "INSERT INTO usuarios VALUES (1, 'Ana', 'Madrid'), (2, 'Carlos', 'Barcelona'), (3, 'María', 'Madrid'), (4, 'Laura', 'Valencia');",
  },
  {
    id: "b15",
    title: "Alias con AS",
    description: "Usa alias para columnas",
    difficulty: "beginner",
    instructions: "Selecciona nombre y email, mostrando 'Nombre' y 'Email' como títulos de columna.",
    hint: "SELECT nombre AS 'Nombre', email AS 'Email'",
    solution: "SELECT nombre AS \"Nombre\", email AS \"Email\" FROM usuarios;",
    explanation: "AS asigna un alias temporal a una columna.",
    tableSchema: "usuarios (id INT, nombre TEXT, email TEXT)",
    initialData: "INSERT INTO usuarios VALUES (1, 'Ana', 'ana@email.com'), (2, 'Carlos', 'carlos@email.com');",
  },
  {
    id: "b16",
    title: "COUNT",
    description: "Cuenta el total de usuarios",
    difficulty: "beginner",
    instructions: "Cuenta cuántos usuarios hay en total.",
    hint: "SELECT COUNT(*) FROM usuarios",
    solution: "SELECT COUNT(*) as total FROM usuarios;",
    explanation: "COUNT(*) cuenta todas las filas de la tabla.",
    tableSchema: "usuarios (id INT, nombre TEXT, email TEXT)",
    initialData: "INSERT INTO usuarios VALUES (1, 'Ana', 'ana@email.com'), (2, 'Carlos', 'carlos@email.com'), (3, 'María', 'maria@email.com');",
  },
  {
    id: "b17",
    title: "GROUP BY básico",
    description: "Cuenta usuarios por ciudad",
    difficulty: "beginner",
    instructions: "Cuenta cuántos usuarios hay en cada ciudad.",
    hint: "GROUP BY ciudad",
    solution: "SELECT ciudad, COUNT(*) as total FROM usuarios GROUP BY ciudad;",
    explanation: "GROUP BY agrupa filas con valores iguales.",
    tableSchema: "usuarios (id INT, nombre TEXT, ciudad TEXT)",
    initialData: "INSERT INTO usuarios VALUES (1, 'Ana', 'Madrid'), (2, 'Carlos', 'Barcelona'), (3, 'María', 'Madrid'), (4, 'Laura', 'Valencia');",
  },
  {
    id: "b18",
    title: "ORDER BY + LIMIT",
    description: "Top 2 usuarios más jóvenes",
    difficulty: "beginner",
    instructions: "Obtén los 2 usuarios más jóvenes (menor edad).",
    hint: "ORDER BY edad ASC LIMIT 2",
    solution: "SELECT nombre, edad FROM usuarios ORDER BY edad ASC LIMIT 2;",
    explanation: "Combinar ORDER BY y LIMIT es muy útil para tops.",
    tableSchema: "usuarios (id INT, nombre TEXT, edad INT)",
    initialData: "INSERT INTO usuarios VALUES (1, 'Ana', 28), (2, 'Carlos', 32), (3, 'María', 25), (4, 'Pedro', 30);",
  },
  {
    id: "b19",
    title: "IS NULL",
    description: "Encuentra valores nulos",
    difficulty: "beginner",
    instructions: "Encuentra usuarios que no tengan email registrado (email IS NULL).",
    hint: "WHERE email IS NULL",
    solution: "SELECT * FROM usuarios WHERE email IS NULL;",
    explanation: "IS NULL verifica valores nulos. No uses = NULL.",
    tableSchema: "usuarios (id INT, nombre TEXT, email TEXT)",
    initialData: "INSERT INTO usuarios VALUES (1, 'Ana', 'ana@email.com'), (2, 'Carlos', NULL), (3, 'María', 'maria@email.com');",
  },
  {
    id: "b20",
    title: "Funciones de texto",
    description: "Usa UPPER para mayúsculas",
    difficulty: "beginner",
    instructions: "Muestra los nombres de usuarios en mayúsculas.",
    hint: "SELECT UPPER(nombre) FROM usuarios",
    solution: "SELECT UPPER(nombre) as nombre_mayusculas FROM usuarios;",
    explanation: "UPPER() convierte texto a mayúsculas.",
    tableSchema: "usuarios (id INT, nombre TEXT)",
    initialData: "INSERT INTO usuarios VALUES (1, 'Ana'), (2, 'Carlos'), (3, 'María');",
  },
];

export const intermediateExercises: Exercise[] = [
  {
    id: "i1",
    title: "INNER JOIN",
    description: "Combina usuarios con sus pedidos",
    difficulty: "intermediate",
    instructions: "Obtén el nombre del usuario y el total de cada pedido usando INNER JOIN.",
    hint: "SELECT u.nombre, p.total FROM usuarios u INNER JOIN pedidos p ON u.id = p.usuario_id",
    solution: "SELECT u.nombre, p.total FROM usuarios u INNER JOIN pedidos p ON u.id = p.usuario_id;",
    explanation: "INNER JOIN devuelve solo filas con coincidencia en ambas tablas.",
    tableSchema: "usuarios (id INT, nombre TEXT)\npedidos (id INT, usuario_id INT, total DECIMAL)",
    initialData: "INSERT INTO usuarios VALUES (1, 'Ana'), (2, 'Carlos'), (3, 'María');\nINSERT INTO pedidos VALUES (1, 1, 150.00), (2, 1, 200.00), (3, 2, 75.50);",
  },
  {
    id: "i2",
    title: "LEFT JOIN",
    description: "Usuarios con o sin pedidos",
    difficulty: "intermediate",
    instructions: "Obtén todos los usuarios y sus pedidos (incluyendo usuarios sin pedidos).",
    hint: "LEFT JOIN para incluir todos los usuarios",
    solution: "SELECT u.nombre, COALESCE(p.total, 0) as total FROM usuarios u LEFT JOIN pedidos p ON u.id = p.usuario_id;",
    explanation: "LEFT JOIN devuelve todas las filas de la izquierda aunque no tengan match.",
    tableSchema: "usuarios (id INT, nombre TEXT)\npedidos (id INT, usuario_id INT, total DECIMAL)",
    initialData: "INSERT INTO usuarios VALUES (1, 'Ana'), (2, 'Carlos'), (3, 'María');\nINSERT INTO pedidos VALUES (1, 1, 150.00);",
  },
  {
    id: "i3",
    title: "Subconsulta escalar",
    description: "Productos sobre el precio promedio",
    difficulty: "intermediate",
    instructions: "Encuentra productos con precio superior al promedio.",
    hint: "WHERE precio > (SELECT AVG(precio) FROM productos)",
    solution: "SELECT nombre, precio FROM productos WHERE precio > (SELECT AVG(precio) FROM productos);",
    explanation: "Una subconsulta escalar devuelve un único valor.",
    tableSchema: "productos (id INT, nombre TEXT, precio DECIMAL)",
    initialData: "INSERT INTO productos VALUES (1, 'Laptop', 2999), (2, 'Mouse', 29), (3, 'Monitor', 899), (4, 'Teclado', 149);",
  },
  {
    id: "i4",
    title: "Subconsulta con IN",
    description: "Usuarios con pedidos caros",
    difficulty: "intermediate",
    instructions: "Encuentra usuarios que hayan hecho pedidos de más de 100.",
    hint: "WHERE id IN (SELECT usuario_id FROM pedidos WHERE total > 100)",
    solution: "SELECT nombre FROM usuarios WHERE id IN (SELECT usuario_id FROM pedidos WHERE total > 100);",
    explanation: "IN con subconsulta filtra por una lista de valores.",
    tableSchema: "usuarios (id INT, nombre TEXT)\npedidos (id INT, usuario_id INT, total DECIMAL)",
    initialData: "INSERT INTO usuarios VALUES (1, 'Ana'), (2, 'Carlos'), (3, 'María');\nINSERT INTO pedidos VALUES (1, 1, 150), (2, 2, 75), (3, 1, 200);",
  },
  {
    id: "i5",
    title: "CASE WHEN",
    description: "Clasifica productos por precio",
    difficulty: "intermediate",
    instructions: "Clasifica productos como 'Barato' (<50), 'Medio' (50-200) o 'Caro' (>200).",
    hint: "Usa CASE WHEN precio < 50 THEN 'Barato' ...",
    solution: "SELECT nombre, precio, CASE WHEN precio < 50 THEN 'Barato' WHEN precio BETWEEN 50 AND 200 THEN 'Medio' ELSE 'Caro' END as categoria FROM productos;",
    explanation: "CASE permite lógica condicional en SQL.",
    tableSchema: "productos (id INT, nombre TEXT, precio DECIMAL)",
    initialData: "INSERT INTO productos VALUES (1, 'Laptop', 2999), (2, 'Mouse', 29), (3, 'Teclado', 149), (4, 'Monitor', 899);",
  },
  {
    id: "i6",
    title: "GROUP BY con HAVING",
    description: "Categorías con más de 2 productos",
    difficulty: "intermediate",
    instructions: "Muestra las categorías que tienen más de 2 productos.",
    hint: "GROUP BY categoria HAVING COUNT(*) > 2",
    solution: "SELECT categoria, COUNT(*) as total FROM productos GROUP BY categoria HAVING COUNT(*) > 2;",
    explanation: "HAVING filtra grupos después de GROUP BY.",
    tableSchema: "productos (id INT, nombre TEXT, categoria TEXT)",
    initialData: "INSERT INTO productos VALUES (1, 'Laptop', 'Electrónicos'), (2, 'Mouse', 'Electrónicos'), (3, 'Camisa', 'Ropa'), (4, 'Monitor', 'Electrónicos'), (5, 'Pantalón', 'Ropa');",
  },
  {
    id: "i7",
    title: "UNION",
    description: "Combina dos consultas",
    difficulty: "intermediate",
    instructions: "Obtén una lista combinada de nombres de usuarios y nombres de productos.",
    hint: "SELECT nombre FROM usuarios UNION SELECT nombre FROM productos",
    solution: "SELECT nombre as nombre FROM usuarios UNION SELECT nombre as nombre FROM productos ORDER BY nombre;",
    explanation: "UNION combina resultados eliminando duplicados.",
    tableSchema: "usuarios (id INT, nombre TEXT)\nproductos (id INT, nombre TEXT)",
    initialData: "INSERT INTO usuarios VALUES (1, 'Ana'), (2, 'Carlos');\nINSERT INTO productos VALUES (1, 'Monitor'), (2, 'Ana');",
  },
  {
    id: "i8",
    title: "Vista",
    description: "Crear una vista de usuarios activos",
    difficulty: "intermediate",
    instructions: "Crea una vista llamada 'usuarios_activos' que muestre nombre y email de usuarios activos.",
    hint: "CREATE VIEW usuarios_activos AS SELECT ...",
    solution: "CREATE VIEW usuarios_activos AS SELECT nombre, email FROM usuarios WHERE activo = true;\nSELECT * FROM usuarios_activos;",
    explanation: "Una vista es una tabla virtual basada en una consulta.",
    tableSchema: "usuarios (id INT, nombre TEXT, email TEXT, activo BOOLEAN)",
    initialData: "INSERT INTO usuarios VALUES (1, 'Ana', 'ana@email.com', true), (2, 'Carlos', 'carlos@email.com', false), (3, 'María', 'maria@email.com', true);",
  },
  {
    id: "i9",
    title: "Funciones agregadas múltiples",
    description: "Estadísticas completas",
    difficulty: "intermediate",
    instructions: "Calcula total, promedio, máximo y mínimo de precios por categoría.",
    hint: "GROUP BY categoria",
    solution: "SELECT categoria, COUNT(*) as total, AVG(precio)::numeric(10,2) as promedio, MAX(precio) as maximo, MIN(precio) as minimo FROM productos GROUP BY categoria;",
    explanation: "Múltiples funciones agregadas en un mismo GROUP BY.",
    tableSchema: "productos (id INT, nombre TEXT, categoria TEXT, precio DECIMAL)",
    initialData: "INSERT INTO productos VALUES (1, 'Laptop', 'Electrónicos', 2999), (2, 'Mouse', 'Electrónicos', 29), (3, 'Camisa', 'Ropa', 45), (4, 'Pantalón', 'Ropa', 89);",
  },
  {
    id: "i10",
    title: "EXISTS",
    description: "Usuarios que han hecho pedidos",
    difficulty: "intermediate",
    instructions: "Encuentra usuarios que hayan realizado al menos un pedido usando EXISTS.",
    hint: "WHERE EXISTS (SELECT 1 FROM pedidos WHERE usuario_id = usuarios.id)",
    solution: "SELECT * FROM usuarios u WHERE EXISTS (SELECT 1 FROM pedidos p WHERE p.usuario_id = u.id);",
    explanation: "EXISTS es más eficiente que IN para subconsultas correlacionadas.",
    tableSchema: "usuarios (id INT, nombre TEXT)\npedidos (id INT, usuario_id INT)",
    initialData: "INSERT INTO usuarios VALUES (1, 'Ana'), (2, 'Carlos'), (3, 'María');\nINSERT INTO pedidos VALUES (1, 1), (2, 1), (3, 2);",
  },
  {
    id: "i11",
    title: "ORDER BY múltiple",
    description: "Ordena por varias columnas",
    difficulty: "intermediate",
    instructions: "Ordena productos por categoría ascendente y precio descendente.",
    hint: "ORDER BY categoria ASC, precio DESC",
    solution: "SELECT nombre, categoria, precio FROM productos ORDER BY categoria ASC, precio DESC;",
    explanation: "Se puede ordenar por múltiples columnas con diferentes direcciones.",
    tableSchema: "productos (id INT, nombre TEXT, categoria TEXT, precio DECIMAL)",
    initialData: "INSERT INTO productos VALUES (1, 'Laptop', 'Electrónicos', 2999), (2, 'Mouse', 'Electrónicos', 29), (3, 'Camisa', 'Ropa', 45);",
  },
  {
    id: "i12",
    title: "COALESCE",
    description: "Maneja valores nulos",
    difficulty: "intermediate",
    instructions: "Muestra el email de usuarios, pero si es NULL muestra 'Sin email'.",
    hint: "COALESCE(email, 'Sin email')",
    solution: "SELECT nombre, COALESCE(email, 'Sin email') as email FROM usuarios;",
    explanation: "COALESCE devuelve el primer valor no nulo de la lista.",
    tableSchema: "usuarios (id INT, nombre TEXT, email TEXT)",
    initialData: "INSERT INTO usuarios VALUES (1, 'Ana', 'ana@email.com'), (2, 'Carlos', NULL), (3, 'María', 'maria@email.com');",
  },
];

export const advancedExercises: Exercise[] = [
  {
    id: "a1",
    title: "CTE simple",
    description: "Usa WITH para crear una consulta temporal",
    difficulty: "advanced",
    instructions: "Usa un CTE para obtener usuarios con más de 1 pedido.",
    hint: "WITH resumen AS (SELECT usuario_id, COUNT(*) as total FROM pedidos GROUP BY usuario_id)",
    solution: "WITH resumen AS (SELECT usuario_id, COUNT(*) as total FROM pedidos GROUP BY usuario_id) SELECT u.nombre, r.total FROM usuarios u JOIN resumen r ON u.id = r.usuario_id WHERE r.total > 1;",
    explanation: "CTE mejora la legibilidad de consultas complejas.",
    tableSchema: "usuarios (id INT, nombre TEXT)\npedidos (id INT, usuario_id INT)",
    initialData: "INSERT INTO usuarios VALUES (1, 'Ana'), (2, 'Carlos'), (3, 'María');\nINSERT INTO pedidos VALUES (1, 1), (2, 1), (3, 2), (4, 2), (5, 3);",
  },
  {
    id: "a2",
    title: "CTE Recursivo",
    description: "Genera una secuencia de números",
    difficulty: "advanced",
    instructions: "Usa un CTE recursivo para generar números del 1 al 10.",
    hint: "WITH RECURSIVE numeros AS (SELECT 1 as n UNION ALL SELECT n+1 FROM numeros WHERE n < 10)",
    solution: "WITH RECURSIVE numeros AS (SELECT 1 as n UNION ALL SELECT n + 1 FROM numeros WHERE n < 10) SELECT * FROM numeros;",
    explanation: "CTE recursivo se llama a sí mismo hasta cumplir la condición.",
  },
  {
    id: "a3",
    title: "ROW_NUMBER",
    description: "Ranking de productos por precio",
    difficulty: "advanced",
    instructions: "Asigna un número de fila a cada producto ordenado por precio descendente.",
    hint: "ROW_NUMBER() OVER (ORDER BY precio DESC)",
    solution: "SELECT nombre, precio, ROW_NUMBER() OVER (ORDER BY precio DESC) as ranking FROM productos;",
    explanation: "ROW_NUMBER() asigna un número único a cada fila en la partición.",
    tableSchema: "productos (id INT, nombre TEXT, precio DECIMAL)",
    initialData: "INSERT INTO productos VALUES (1, 'Laptop', 2999), (2, 'Mouse', 29), (3, 'Monitor', 899), (4, 'Teclado', 149);",
  },
  {
    id: "a4",
    title: "RANK",
    description: "Ranking con empates",
    difficulty: "advanced",
    instructions: "Rankea productos por precio, permitiendo empates.",
    hint: "RANK() OVER (ORDER BY precio DESC)",
    solution: "SELECT nombre, precio, RANK() OVER (ORDER BY precio DESC) as ranking FROM productos;",
    explanation: "RANK() permite empates y salta posiciones.",
    tableSchema: "productos (id INT, nombre TEXT, precio DECIMAL)",
    initialData: "INSERT INTO productos VALUES (1, 'Laptop', 2999), (2, 'Mouse', 29), (3, 'Monitor', 899), (4, 'Teclado', 29);",
  },
  {
    id: "a5",
    title: "LAG",
    description: "Compara con el registro anterior",
    difficulty: "advanced",
    instructions: "Muestra el precio de cada producto y el precio del producto anterior ordenado por precio.",
    hint: "LAG(precio) OVER (ORDER BY precio)",
    solution: "SELECT nombre, precio, LAG(precio) OVER (ORDER BY precio) as precio_anterior FROM productos;",
    explanation: "LAG() accede al valor de la fila anterior en la ventana.",
    tableSchema: "productos (id INT, nombre TEXT, precio DECIMAL)",
    initialData: "INSERT INTO productos VALUES (1, 'Laptop', 2999), (2, 'Mouse', 29), (3, 'Monitor', 899), (4, 'Teclado', 149);",
  },
  {
    id: "a6",
    title: "Trigger para actualizar fecha",
    description: "Crea un trigger que actualice la fecha de modificación",
    difficulty: "advanced",
    instructions: "Crea una función y un trigger que actualice fecha_modificacion en cada UPDATE de usuarios.",
    hint: "CREATE OR REPLACE FUNCTION ... RETURNS TRIGGER ...",
    solution: "CREATE OR REPLACE FUNCTION set_fecha_mod() RETURNS TRIGGER AS $$ BEGIN NEW.fecha_modificacion = NOW(); RETURN NEW; END; $$ LANGUAGE plpgsql;\nCREATE TRIGGER trg_fecha_mod BEFORE UPDATE ON usuarios FOR EACH ROW EXECUTE FUNCTION set_fecha_mod();",
    explanation: "Los triggers automatizan acciones en eventos de la BD.",
  },
  {
    id: "a7",
    title: "Procedimiento almacenado",
    description: "Crea un procedimiento para registrar usuarios",
    difficulty: "advanced",
    instructions: "Crea un procedimiento que inserte un usuario validando que el email no exista.",
    hint: "CREATE OR REPLACE PROCEDURE ...",
    solution: "CREATE OR REPLACE PROCEDURE registrar_usuario(p_nombre TEXT, p_email TEXT) LANGUAGE plpgsql AS $$ BEGIN IF EXISTS (SELECT 1 FROM usuarios WHERE email = p_email) THEN RAISE EXCEPTION 'Email ya existe'; END IF; INSERT INTO usuarios (nombre, email) VALUES (p_nombre, p_email); END; $$;",
    explanation: "Los procedimientos encapsulan lógica de negocio en la BD.",
  },
  {
    id: "a8",
    title: "Función escalar",
    description: "Función para calcular IVA",
    difficulty: "advanced",
    instructions: "Crea una función que calcule el precio con IVA (21%).",
    hint: "CREATE FUNCTION calcular_iva(precio DECIMAL) RETURNS DECIMAL",
    solution: "CREATE OR REPLACE FUNCTION calcular_iva(precio DECIMAL) RETURNS DECIMAL LANGUAGE plpgsql AS $$ BEGIN RETURN precio * 1.21; END; $$;\nSELECT nombre, precio, calcular_iva(precio) as con_iva FROM productos;",
    explanation: "Las funciones devuelven un valor y pueden usarse en SELECT.",
    tableSchema: "productos (id INT, nombre TEXT, precio DECIMAL)",
    initialData: "INSERT INTO productos VALUES (1, 'Laptop', 1000), (2, 'Mouse', 25);",
  },
  {
    id: "a9",
    title: "Índice parcial",
    description: "Índice solo para usuarios activos",
    difficulty: "advanced",
    instructions: "Crea un índice parcial en email solo para usuarios activos.",
    hint: "CREATE INDEX ... ON usuarios(email) WHERE activo = true",
    solution: "CREATE INDEX idx_usuarios_activos_email ON usuarios(email) WHERE activo = true;",
    explanation: "Los índices parciales ahorran espacio y mejoran rendimiento.",
  },
  {
    id: "a10",
    title: "JSONB query",
    description: "Consulta datos JSONB",
    difficulty: "advanced",
    instructions: "Busca productos cuya marca sea 'Dell' y tengan 16GB de RAM en el campo metadata JSONB.",
    hint: "metadata @> '{\"marca\": \"Dell\", \"ram\": 16}'",
    solution: "SELECT nombre, metadata FROM productos WHERE metadata @> '{\"marca\": \"Dell\", \"ram\": 16}';",
    explanation: "El operador @> verifica si JSONB contiene el par clave-valor.",
    tableSchema: "productos (id INT, nombre TEXT, metadata JSONB)",
    initialData: "INSERT INTO productos VALUES (1, 'Laptop Dell', '{\"marca\": \"Dell\", \"ram\": 16, \"color\": \"gris\"}'), (2, 'Monitor Dell', '{\"marca\": \"Dell\", \"ram\": 0}'), (3, 'Laptop HP', '{\"marca\": \"HP\", \"ram\": 16}');",
  },
];
